monolog:
    handlers:
        # Загальний обробник для запису логів в файл
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            channels: ['!event'] # Виключає події з логування
        # Може бути доданий додатковий обробник, наприклад для логування в консоль або syslog
        # console:
        #     type: console
        #     level: info
        #     channels: ['!event']
        # syslog:
        #     type: syslog
        #     level: info
        #     channels: ['!event']
