version: '3.3'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lightbot-api
        environment:
            APP_ENV: prod
            DATABASE_URL: mysql://lightbot:uon5j21211@mysql:3306/lightbot
        volumes:
            - .:/var/www/html
        networks:
            - backend

    mysql:
        image: mysql:8.0
        container_name: lightbot-db
        environment:
            MYSQL_ROOT_PASSWORD: Siromiashka!802
            MYSQL_DATABASE: lightbot
            MYSQL_USER: lightbot
            MYSQL_PASSWORD: uon5j21211
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

    nginx:
        image: nginx:latest
        container_name: lightbot-nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=api.bondarenkoid.dev
            - VIRTUAL_PORT=80
        networks:
            - backend

networks:
    backend:
        external: true

volumes:
    mysql_data:
