monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            channels: ['!event']
        # Можна додати додаткові обробники, якщо потрібно
        # Наприклад, для логування в сторонні сервіси або системи
        # syslog:
        #     type: syslog
        #     level: error
        #     channels: ['!event']
        # error_log:
        #     type: error_log
        #     level: error
        #     channels: ['!event']
        # Додатковий обробник для випадків, коли ви хочете логувати всі повідомлення помилок
        # exception:
        #     type: stream
        #     path: '%kernel.logs_dir%/exception.log'
        #     level: error
        #     channels: ['exception']
