#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/auth/login

api_refresh_token:
    path: /api/auth/refresh

light_status:
    resource: '../src/Controller/StatusController.php'
    type: attribute

day:
    resource: '../src/Controller/DayController.php'
    type: attribute

timeslots:
    resource: '../src/Controller/TimeSlotController.php'
    type: attribute

telegram:
    resource: '../src/Controller/TelegramController.php'
    type: attribute