#!/bin/sh

# Визначаємо директорію проєкту
PROJECT_DIR=$(git rev-parse --show-toplevel)

# Отримуємо список змінених PHP файлів, які додані до індексації
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.php$')

# Якщо є змінені файли, виконуємо перевірку
if [ -n "$STAGED_FILES" ]; then
    echo "Running PHP CS Fixer..."

    # Запускаємо PHP CS Fixer для перевірки та виправлення тільки доданих до індексації файлів
    php "$PROJECT_DIR/vendor/bin/php-cs-fixer" fix --config="$PROJECT_DIR/.php-cs-fixer.php" --verbose --using-cache=no $STAGED_FILES

    # Повторно додаємо виправлені файли до індексації
    git add $STAGED_FILES

    # Перевіряємо результат виконання PHP CS Fixer
    FIXER_STATUS=$?
    if [ $FIXER_STATUS -ne 0 ]; then
        echo "PHP CS Fixer found issues and attempted to fix them. Please review changes before committing."
        exit 1
    fi
fi

# Якщо немає помилок, дозволяємо коміт
exit 0
